name: Github-Action-Test
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub2/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Action Script
        run: yarn run action
