name: sub-module3
on:
  push:
    branches:
      - master
    paths:
      - "packages/sub3/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Action Script
        run: yarn sub3 run action
